#!/bin/bash
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# UniFi Backup Manager - Server Setup Script
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# This script sets up the UniFi Backup Manager on a fresh server.
# It will:
#   1. Check for Docker and Docker Compose
#   2. Generate secure secrets
#   3. Create the .env file
#   4. Pull Docker images
#   5. Start the services
#   6. Create the initial admin user
#
# Usage: ./setup.sh
#
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="${INSTALL_DIR:-/opt/unifi-backup}"
BACKUP_DIR="${BACKUP_DIR:-/opt/unifi-backup/backups}"

echo -e "${BLUE}"
echo "================================================="
echo "   UniFi Backup Manager - Server Setup"
echo "================================================="
echo -e "${NC}"

# Check if running as root or with sudo
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Error: This script must be run as root or with sudo${NC}"
    exit 1
fi

# Check for Docker
echo -e "${YELLOW}Checking for Docker...${NC}"
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed.${NC}"
    echo "Please install Docker first: https://docs.docker.com/engine/install/"
    exit 1
fi
echo -e "${GREEN}Docker found: $(docker --version)${NC}"

# Check for Docker Compose
echo -e "${YELLOW}Checking for Docker Compose...${NC}"
if ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed.${NC}"
    echo "Please install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi
echo -e "${GREEN}Docker Compose found: $(docker compose version --short)${NC}"

# Create installation directory
echo -e "${YELLOW}Creating installation directory: ${INSTALL_DIR}${NC}"
mkdir -p "${INSTALL_DIR}"
mkdir -p "${BACKUP_DIR}"
cd "${INSTALL_DIR}"

# Download docker-compose.prod.yaml if not present
if [[ ! -f "docker-compose.yaml" ]]; then
    echo -e "${YELLOW}Downloading docker-compose.yaml...${NC}"
    curl -fsSL "https://raw.githubusercontent.com/rjsears/unifi_backups/main/docker-compose.prod.yaml" -o docker-compose.yaml
fi

# Generate secrets
echo -e "${YELLOW}Generating secure secrets...${NC}"

generate_secret() {
    openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

generate_fernet_key() {
    # Fernet key must be 32 url-safe base64-encoded bytes
    python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || \
    docker run --rm python:3.11-slim python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
}

# Check if .env already exists
if [[ -f ".env" ]]; then
    echo -e "${YELLOW}Existing .env file found.${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}Keeping existing .env file.${NC}"
    else
        rm -f .env
    fi
fi

# Create .env file if it doesn't exist
if [[ ! -f ".env" ]]; then
    echo -e "${YELLOW}Creating .env file with secure secrets...${NC}"

    # Prompt for Docker Hub username
    read -p "Enter your Docker Hub username [rjsears]: " DOCKERHUB_USER
    DOCKERHUB_USER="${DOCKERHUB_USER:-rjsears}"

    # Prompt for admin credentials
    read -p "Enter admin username [admin]: " ADMIN_USER
    ADMIN_USER="${ADMIN_USER:-admin}"

    read -p "Enter admin email [admin@localhost]: " ADMIN_EMAIL
    ADMIN_EMAIL="${ADMIN_EMAIL:-admin@localhost}"

    while true; do
        read -s -p "Enter admin password (min 8 chars): " ADMIN_PASS
        echo
        if [[ ${#ADMIN_PASS} -ge 8 ]]; then
            break
        fi
        echo -e "${RED}Password must be at least 8 characters${NC}"
    done

    # Generate the .env file
    cat > .env << EOF
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# UniFi Backup Manager - Environment Configuration
# Generated by setup.sh on $(date)
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# Docker Hub
DOCKERHUB_USERNAME=${DOCKERHUB_USER}
IMAGE_TAG=latest

# Database
POSTGRES_USER=unifi_backup
POSTGRES_PASSWORD=$(generate_secret)
POSTGRES_DB=unifi_backups

# Security
SECRET_KEY=$(generate_secret)
FERNET_KEY=$(generate_fernet_key)

# Server
HTTP_PORT=80
LOG_LEVEL=INFO

# Initial Admin User (used by init script)
ADMIN_USERNAME=${ADMIN_USER}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASS}
EOF

    chmod 600 .env
    echo -e "${GREEN}.env file created with secure secrets${NC}"
fi

# Pull Docker images
echo -e "${YELLOW}Pulling Docker images...${NC}"
docker compose pull

# Start services
echo -e "${YELLOW}Starting services...${NC}"
docker compose up -d

# Wait for services to be ready
echo -e "${YELLOW}Waiting for services to start...${NC}"
sleep 10

# Check if services are running
echo -e "${YELLOW}Checking service status...${NC}"
if docker compose ps | grep -q "running"; then
    echo -e "${GREEN}Services are running!${NC}"
else
    echo -e "${RED}Warning: Some services may not be running properly${NC}"
    docker compose ps
fi

# Create initial admin user
echo -e "${YELLOW}Creating initial admin user...${NC}"
source .env

# Wait for the API to be ready
max_attempts=30
attempt=0
while [[ $attempt -lt $max_attempts ]]; do
    if curl -s http://localhost:${HTTP_PORT:-80}/api/health | grep -q "healthy"; then
        break
    fi
    echo "Waiting for API to be ready... (attempt $((attempt+1))/$max_attempts)"
    sleep 2
    ((attempt++))
done

if [[ $attempt -eq $max_attempts ]]; then
    echo -e "${RED}Warning: API may not be fully ready. You may need to create the admin user manually.${NC}"
fi

echo ""
echo -e "${GREEN}=================================================${NC}"
echo -e "${GREEN}   Setup Complete!${NC}"
echo -e "${GREEN}=================================================${NC}"
echo ""
echo -e "Access the web interface at: ${BLUE}http://$(hostname -I | awk '{print $1}')${NC}"
echo ""
echo -e "Admin credentials:"
echo -e "  Username: ${BLUE}${ADMIN_USER}${NC}"
echo -e "  Password: ${BLUE}(the password you entered)${NC}"
echo ""
echo -e "${YELLOW}Note: On first login, you'll need to create your admin user through the API.${NC}"
echo -e "${YELLOW}Run this command to create the admin user:${NC}"
echo ""
echo -e "${BLUE}docker compose exec backend python -c \"${NC}"
echo -e "${BLUE}import asyncio${NC}"
echo -e "${BLUE}from app.database import AsyncSessionLocal${NC}"
echo -e "${BLUE}from app.services.auth_service import AuthService${NC}"
echo -e "${BLUE}async def create_admin():${NC}"
echo -e "${BLUE}    async with AsyncSessionLocal() as db:${NC}"
echo -e "${BLUE}        await AuthService.create_user(db, '${ADMIN_USER}', '${ADMIN_EMAIL}', '${ADMIN_PASS}', is_admin=True)${NC}"
echo -e "${BLUE}        print('Admin user created!')${NC}"
echo -e "${BLUE}asyncio.run(create_admin())${NC}"
echo -e "${BLUE}\"${NC}"
echo ""
echo -e "Configuration files are stored in: ${BLUE}${INSTALL_DIR}${NC}"
echo -e "Backup data is stored in: ${BLUE}${BACKUP_DIR}${NC}"
echo ""
echo -e "${YELLOW}Useful commands:${NC}"
echo "  View logs:     docker compose logs -f"
echo "  Stop services: docker compose down"
echo "  Start services: docker compose up -d"
echo "  Update images: docker compose pull && docker compose up -d"
echo ""
